# Execute repository tests.
name: Tests

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        houdini-version: ["20.5", "21.0"]

    container:
      image: captainhammy/hython-runner:${{ matrix.houdini-version }}

    steps:
      - name: Mark workspace as safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup licensing
        uses: captainhammy/setup-hserver-action@v1
        with:
          server: ${{ secrets.LICENSE_SERVER }}
          client_id: ${{ secrets.SESI_CLIENT_ID }}
          client_secret_key: ${{ secrets.SESI_SECRET_KEY }}

      - name: Install dependencies
        run: python3 -m pip install tox tox-gh-actions coverage

      - name: Test with tox
        run: tox

      # Build package for rez testing
      - name: Build Package
        uses: captainhammy/build-rez-package-action@v1

      # Test rez package
      - name: Test Current Rez Package
        uses: captainhammy/test-rez-package-action@v1

      # Test the package using the Houdini package .json file to ensure it works
      - name: Test Houdini package json
        env:
          HOUDINI_PACKAGE_DIR: ${{ github.workspace }}
        run: |
          hython -m pip install -r requirements.txt -r test_requirements.txt
          hython -m pytest tests/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
