# Execute repository tests.
name: Tests

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        houdini-version: ["20.5", "21.0"]

    container:
      image: captainhammy/hython-runner:${{ matrix.houdini-version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup licensing
        uses: captainhammy/setup-hserver-action@v1
        with:
          server: ${{ secrets.LICENSE_SERVER }}
          client_id: ${{ secrets.SESI_CLIENT_ID }}
          client_secret_key: ${{ secrets.SESI_SECRET_KEY }}

      - name: Install dependencies
        run: python3 -m pip install tox tox-gh-actions coverage

#      - name: Test with tox
#        run: tox
#
#      # Build package for rez testing
#      - name: Build Package
#        uses: captainhammy/build-rez-package-action@v1
#
#      # Test rez package
#      - name: Test Current Rez Package
#        uses: captainhammy/test-rez-package-action@v1

      - name: Test Houdini package json
        env:
          HOUDINI_PACKAGE_DIR: ${{ github.workspace }}
        run: |
          echo $HOUDINI_PACKAGE_DIR
          python3 -m pip install -r requirements.txt
          hython -m pip install pytest pytest-cov pytest-datadir pytest-houdini pytest-mock 
          hython -m pytest tests/

      - name: Workaround for codecov/feedback#263
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
